FROM python:3.8.10-slim
COPY ./requirements.txt /app/requirements.txt
# TODO: add pip version or replace to poetry
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt
WORKDIR /code
COPY . /code