version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: on-failure

  service:
    container_name: service
    build: .
    command: python main.py
    ports:
      - "5002:5002"
    volumes:
      - .:/code
    depends_on:
      - postgres
    mem_reservation: 4096M
    restart: on-failure
